In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import seaborn as sns

In [4]:
df = pd.read_csv("CRMLSListing202602.csv")
df.head()

,OriginalListPrice,ListingKey,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,PropertyType,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1
0,630000.0,1155889366,NaN,NaN,James,Tran,33.966301,-117.238653,10625 Aster Leaf,Residential,...,5.0,False,3.0,Moreno Valley Unified,92557,NaN,0.00,10019.0,NaN,10625 Aster Leaf
1,1099000.0,1155889183,NaN,NaN,Bailey,Tarr,32.897005,-117.167538,10423 Adamson Way,Residential,...,1.0,False,2.0,San Diego Unified,92126,NaN,303.25,NaN,NaN,10423 Adamson Way
2,499000.0,1155888472,NaN,NaN,Edward,Kaminsky,33.831316,-118.376615,641 S Prospect Avenue 103,Residential,...,1.0,False,1.0,Redondo Unified,90277,NaN,610.00,161493.0,NaN,641 S Prospect Avenue 103
3,2000000.0,1155888254,NaN,NaN,Mary,Bell,33.777977,-117.798519,19151 Fowler,Residential,...,1.0,False,3.0,Tustin Unified,92705,NaN,0.00,19700.0,NaN,19151 Fowler
4,2250000.0,1155888060,2026-03-25,2250000.0,Jeff,McConville,33.634020,-117.909194,1809 Tustin,Residential,...,3.0,False,2.0,Newport Mesa Unified,92627,Douglas Elliman Of California,0.00,6970.0,NaN,1809 Tustin

In [17]:
df.shape

(32353, 81)

In [5]:
df.columns

Index(['OriginalListPrice', 'ListingKey', 'CloseDate', 'ClosePrice',
       'ListAgentFirstName', 'ListAgentLastName', 'Latitude', 'Longitude',
       'UnparsedAddress', 'PropertyType', 'LivingArea', 'ListPrice',
       'DaysOnMarket', 'ListOfficeName', 'BuyerOfficeName', 'CoListOfficeName',
       'ListAgentFullName', 'CoListAgentFirstName', 'CoListAgentLastName',
       'BuyerAgentMlsId', 'BuyerAgentFirstName', 'BuyerAgentLastName',
       'FireplacesTotal', 'AssociationFeeFrequency', 'AboveGradeFinishedArea',
       'ListingKeyNumeric', 'MLSAreaMajor', 'TaxAnnualAmount',
       'CountyOrParish', 'PropertyType.1', 'MlsStatus', 'ElementarySchool',
       'ListAgentFirstName.1', 'AttachedGarageYN', 'ParkingTotal',
       'BuilderName', 'PropertySubType', 'LotSizeAcres', 'SubdivisionName',
       'BuyerOfficeAOR', 'YearBuilt', 'DaysOnMarket.1', 'StreetNumberNumeric',
       'LivingArea.1', 'ListingId', 'BathroomsTotalInteger', 'City', 'TaxYear',
       'BuildingAreaTotal', 'BedroomsTotal', 'ContractStatusChangeDate',
       'Longitude.1', 'ElementarySchoolDistrict', 'CoBuyerAgentFirstName',
       'PurchaseContractDate', 'ListingContractDate', 'BelowGradeFinishedArea',
       'BusinessType', 'Latitude.1', 'ListPrice.1', 'StateOrProvince',
       'CoveredSpaces', 'MiddleOrJuniorSchool', 'FireplaceYN', 'Stories',
       'HighSchool', 'Levels', 'ListAgentLastName.1', 'CloseDate.1',
       'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'BuyerOfficeName.1', 'AssociationFee', 'LotSizeSquareFeet',
       'MiddleOrJuniorSchoolDistrict', 'UnparsedAddress.1'],
      dtype='object')

In [6]:
df.describe()

,OriginalListPrice,ListingKey,ClosePrice,Latitude,Longitude,LivingArea,ListPrice,DaysOnMarket,FireplacesTotal,AboveGradeFinishedArea,...,Latitude.1,ListPrice.1,CoveredSpaces,Stories,LotSizeArea,MainLevelBedrooms,GarageSpaces,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict
count,3.221900e+04,3.235300e+04,6.540000e+03,31875.000000,31887.000000,27994.000000,3.226200e+04,32353.000000,0.0,0.0,...,31875.000000,3.226200e+04,0.0,23897.000000,2.960400e+04,15007.000000,25836.000000,22479.000000,2.956200e+04,0.0
mean,1.121162e+06,1.153098e+09,7.737355e+05,34.566048,-118.427221,1935.097253,1.033634e+06,16.372114,NaN,NaN,...,34.566048,1.033634e+06,NaN,1.364648,9.487170e+04,1.920104,1.725886,223.062698,3.986607e+05,NaN
std,7.180938e+06,8.464752e+05,1.212817e+06,1.655698,3.597770,1612.617770,2.251182e+06,15.750910,NaN,NaN,...,1.655698,2.251182e+06,NaN,0.481341,3.803553e+06,1.505714,2.832798,471.139860,1.601624e+07,NaN
min,1.000000e+00,1.063377e+09,1.770000e+00,0.000000,-155.633577,0.000000,1.000000e+00,-17.000000,NaN,NaN,...,0.000000,1.000000e+00,NaN,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,NaN
25%,1.300000e+05,1.152613e+09,4.295000e+03,33.760202,-118.554382,1175.000000,1.300000e+05,5.000000,NaN,NaN,...,33.760202,1.300000e+05,NaN,1.000000,4.977750e+03,1.000000,1.000000,0.000000,5.292000e+03,NaN
50%,6.499000e+05,1.153092e+09,5.350000e+05,34.056781,-118.112253,1604.000000,6.490000e+05,13.000000,NaN,NaN,...,34.056781,6.490000e+05,NaN,1.000000,7.373000e+03,2.000000,2.000000,0.000000,7.613000e+03,NaN
75%,1.198000e+06,1.153435e+09,1.100000e+06,34.431280,-117.292902,2263.000000,1.195000e+06,26.000000,NaN,NaN,...,34.431280,1.195000e+06,NaN,2.000000,1.500000e+04,3.000000,2.000000,356.000000,1.836625e+04,NaN
max,8.195000e+08,1.155889e+09,3.026000e+07,41.891615,118.084350,94619.000000,1.000000e+08,710.000000,NaN,NaN,...,41.891615,1.000000e+08,NaN,2.000000,4.187423e+08,32.000000,400.000000,14220.000000,1.897866e+09,NaN

In [10]:
df.isna().sum()

OriginalListPrice                 134
ListingKey                          0
CloseDate                       24905
ClosePrice                      25813
ListAgentFirstName                167
                                ...
BuyerOfficeName.1               25229
AssociationFee                   9874
LotSizeSquareFeet                2791
MiddleOrJuniorSchoolDistrict    32353
UnparsedAddress.1                  67
Length: 81, dtype: int64

In [11]:
df.dtypes

OriginalListPrice               float64
ListingKey                        int64
CloseDate                        object
ClosePrice                      float64
ListAgentFirstName               object
                                 ...
BuyerOfficeName.1                object
AssociationFee                  float64
LotSizeSquareFeet               float64
MiddleOrJuniorSchoolDistrict    float64
UnparsedAddress.1                object
Length: 81, dtype: object

In [36]:
# check for duplicates
df1 = df.copy()
dupes = [col for col in df1.columns if f"{col}.1" in df1.columns] # duplicates have .1 in name
{col: df1[col].equals(df1[f"{col}.1"]) for col in dupes} # see if they are identical

{'CloseDate': True,
 'ListAgentFirstName': True,
 'ListAgentLastName': True,
 'Latitude': True,
 'Longitude': True,
 'UnparsedAddress': True,
 'PropertyType': True,
 'LivingArea': True,
 'ListPrice': True,
 'DaysOnMarket': True,
 'BuyerOfficeName': True}

In [37]:
# drop duplicates
df1 = df1.drop(columns=[f"{col}.1" for col in dupes])

# check again
dupes = [col for col in df1.columns if f"{col}.1" in df1.columns]
{col: df1[col].equals(df1[f"{col}.1"]) for col in dupes}

{}

In [41]:
print("original shape:", (df.shape))
print("modified shape:", (df1.shape))

original shape: (32353, 81)
modified shape: (32353, 70)

In [56]:
# percent of non na values
dates = [col for col in df1.columns if col.endswith('Date')]
{col: f"{round(100*((df1.shape[0] - df1[col].isna().sum())/df1.shape[0]))}%" for col in dates}

{'CloseDate': '23%',
 'ContractStatusChangeDate': '99%',
 'PurchaseContractDate': '42%',
 'ListingContractDate': '100%'}